apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ template "api-nodejs.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ template "api-nodejs.fullname" . }}
spec:
#  clusterIP: None
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: {{ template "api-nodejs.fullname" . }}
    version: v1.0.0
status:
  loadBalancer: {}

